### ISSUE TITLE
Final visual polish pass

### ISSUE THREAD

**Issue by alexelash** [azavea/ism-watershed-wellness-snapshot#107]
In particular, I noticed a couple of visual issues:
- [ ] Add "You are here" star from designs to map
- [ ] Center the fish in detail views (only visible on iPad)
![Screen Shot 2019-08-08 at 10 53 40 AM](https://user-images.githubusercontent.com/5672295/62713576-f6ffc380-b9ca-11e9-8fcd-615d1b167064.png)
- [ ] Move mapbox and (i) icon to a better location when detail view is open.
![Screen Shot 2019-08-08 at 10 53 32 AM](https://user-images.githubusercontent.com/5672295/62713607-0252ef00-b9cb-11e9-96dd-673a078ab258.png)

**Comment by caseycesari** [comment]
Completed in #115
