### ISSUE TITLE
Change settings for sensor indicating certain health status

### ISSUE THREAD

**Issue by dboyer** [azavea/ism-watershed-wellness-snapshot#116]
Wissahickon - Change the condition for dissolved oxygen over 6 to fair, not bad. 

Delaware Water Gap - Add a fair turbidity reading when the sensor is in the 3.01 to 4 range.

**Comment by fungjj92** [comment]
We will not be able to have custom ranges for good/fair/poor for each watershed; what we could accommodate are changes to indicator values (low, high) or the percentage around the extremes that serve as the breakpoints for g/f/p. Right now we use 10% on the ends.

**Comment by fungjj92** [comment]
Checking in on the status of this card -- have we received a replacement value? Can this issue be closed? @dboyer

**Comment by dboyer** [comment]
1. Text changes below. If you click any map marker and then click the hamburger menu in the top right corner, there is place holder text for these four categories. Please replace with what is below. I believe this text is the same for all locations.

Water Temp
Water temperature affects the growth and reproduction of plants and animals in the water.

Dissolved Oxygen
Dissolved oxygen is a measure of the concentration of oxygen in a body of water. Plants and animals need oxygen to breath underwater.

pH
pH tells us how acidic (below 7.0pH) or basic (above 7.0pH) the water is. This determines if the water is healthy enough to support plants and animals. 

Turbidity 
Turbidity is a measure of the cloudiness of the water. Particles, sediment and pollution may raise turbidity levels. 

Screenshot of current text:

![Screen Shot 2020-01-15 at 9 34 46 AM](https://user-images.githubusercontent.com/516764/72442346-4c11e380-377a-11ea-8514-4e8de61f2b70.png)

**Comment by dboyer** [comment]
2. Adjust the "fair" status for turbidity to only be 10% of the higher end of the value. Fair should not apply to 10% of the lower end of the value.
