### ISSUE TITLE
Replace Azavea-hosted font with one hosted by the client

### ISSUE THREAD

**Issue by alexelash** [azavea/ism-watershed-wellness-snapshot#32]
For the prototype, we are pulling in the font (Filson Soft) using an Azavea Creative Cloud license. When we receive the client's paid-for version, we will need to either update the link or import the fonts in a different way.

**Comment by dboyer** [comment]
@alexelash The client said:

"we licensed the Filson Soft fonts just for use in the 4 digital interactives, but they should also be available through Adobe Fonts/Creative Cloud for print or web use cases"

It sounds like we're already using the Creative Cloud version. Should I ask for an additional license?

**Comment by alexelash** [comment]
Sorry that I missed this. That's great, we are currently using the Creative Cloud version. We'll either need:
- their login, so I can set up a web project
- them to follow the steps [here](https://helpx.adobe.com/fonts/using/add-fonts-website.html) and send the the code from the last step to us. If they want to do it themselves, we need **Bold, Medium** and **Regular** fonts.

**Comment by dboyer** [comment]
user: dkennedy@phillyseaport.org
password: Gridley1898

The embedded code is: <link rel="stylesheet" href="https://use.typekit.net/vyl4wmw.css">

**Comment by caseycesari** [comment]
Done in #112
