### ISSUE TITLE
Handle sensor data fetch errors the same as River Dispatches

### ISSUE THREAD

**Issue by fungjj92** [azavea/ism-watershed-wellness-snapshot#56]
The app requests sensor data from the USGS. Sometimes those requests fail for one reason or another, and we want to handle those failure cases the same way we do in the River Dispatches app.

There’s a main server, and if that doesn’t work we use a fallback/nearby sensor, and if _that_ doesn’t work we use hardcoded values.

https://github.com/azavea/pwd-river-dispatches/blob/48b3a6aa448fd66125dd2cbb1ec0f504346f14ba/usgs-details.html#L259-L270

Hardcoded values for 12 mo. We'd only need 1 value for each variable, instead of 12 (one for each month) as in here: https://github.com/azavea/pwd-river-dispatches/blob/48b3a6aa448fd66125dd2cbb1ec0f504346f14ba/usgs-details.html#L128-L136

The relevant variables are probably those listed in this spreadsheet, not yet confirmed https://docs.google.com/spreadsheets/d/19vqjrmnP_Yi9apkNt5R_OGPkYVXOP5fly17vL6aQqjg/edit?ouid=110437599130106181468&usp=sheets_home&ths=true

Requires #20

**Comment by caseycesari** [comment]
Superseded by #59
