### ISSUE TITLE
Replace placeholder text for sensor condition description.

### ISSUE THREAD

**Issue by caseycesari** [azavea/ism-watershed-wellness-snapshot#80]
We need copy to describe what good/fair/poor health means.

The client should also confirm the copy thorough the rest of the app is good.

![image](https://user-images.githubusercontent.com/1042475/53966862-0dbf8880-40c2-11e9-966c-4cd60683e957.png)

**Comment by caseycesari** [comment]
@alexelash has provided copy for the area under the sensor title on the overview pane.

*Tinicum*

```
The Tinicum site is near the Philadelphia International Airport at the southern-most end of the Delaware River Basin.
```

*Delaware Water Gap*
```
The Delaware Water Gap is where the Delaware River cuts through the Appalachian Mountains.
```

*Wissahickon Creek*
```
Wissahickon Creek runs through Fort Washington State Park before emptying into the Schuylkill River in Philadelphia.
```

**Comment by dboyer** [comment]
The client signed off on the location text included previously in this issue. Updated condition text from the client:

POOR: This means that conditions might be harmful to wildlife. The conditions are not normal compared to other surrounding areas. Conditions could be improved through restoration and protection. 

FAIR: This means that conditions are declining. Conditions indicate that wildlife could be becoming stressed. These areas could be restored to GOOD status.  

GOOD: This means that conditions are ideal for wildlife to thrive. These areas should be protected to preserve this condition.
