### ISSUE TITLE
Make sensor details dialog scrollable

### ISSUE THREAD

**Issue by kellyi** [azavea/ism-watershed-wellness-snapshot#90]
Currently it's not possible to scroll the sensor details dialog:

<img width="964" alt="Screen Shot 2019-03-11 at 8 42 36 PM" src="https://user-images.githubusercontent.com/4165523/54167088-903ba580-443e-11e9-964d-ff9b06d250f6.png">

Noticed this in both Firefox and Safari.

**Comment by alexelash** [comment]
@kellyi @caseycesari Interesting. It scrolls fine on iPad Safari.

**Comment by kellyi** [comment]
Interesting. I noticed the scroll problem on desktop Firefox. Just double checked and it still has the same quirk. We can de-prioritize this if the iPad's the only real target, though!

**Comment by caseycesari** [comment]
Yeah, very annoying, but I think we have to hold for now.

**Comment by dboyer** [comment]
Let's take care of this soon - perhaps part of #92

**Comment by dboyer** [comment]
@alexelash Here's one design related ISM task that popped up since our conversation yesterday. If you have time, could you look at it?
