### ISSUE TITLE
Blackbox

### ISSUE THREAD

**Issue by fungjj92** [azavea/ism-watershed-wellness-snapshot#92]
Cards to be determined based on client emails. Pending sifting through client emails.

**Comment by fungjj92** [comment]
1 point allotted to #79.

2 points remaining for sprint 7/26-8/8

**Comment by caseycesari** [comment]
-1 for https://github.com/azavea/ism-watershed-wellness-snapshot/issues/103

**Comment by caseycesari** [comment]
-1 for https://github.com/azavea/ism-watershed-wellness-snapshot/issues/93
